name: go build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14.4'

      - run: go build -v -ldflags "-s -w" -o ./gospy ./cmd/gospy/main.go

      - run: go build -v -ldflags "-s -w" -o ./gospyserver ./cmd/gospyserver/main.go
